# This is a basic workflow to help you get started with Actions

name: minecraft_server_backup

# Controls when the workflow will run
on: 
  #schedule:
  #  - cron: "01 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull_changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install lftp
        run: |
          echo "fish:auto-confirm" > ~/.lftprc
          sudo apt install lftp >/dev/null 2>&1
          which lftp && \
          $(which lftp) -c "set ssl:verify-certificate false; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}; mirror -n -v / ." || \
          echo "lftp not installed"
      
