# This is a basic workflow to help you get started with Actions

name: minecraft_server_backup

# Controls when the workflow will run
on: 
  #schedule:
  #  - cron: "01 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download-files-from-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: do we have rsync
        run: |
          export DIR="/1. SeanPauls Family Minecraft Serve/"
          export PASS='oMV9oHNWyb'
          export HOST='sftp.shockbyte.bhs1.shockbyte.host'
          export USER='seanpaul.bobadilla@gmail.com'
          sshpass -p ${PASS} sftp -4rv -o StrictHostKeyChecking=no -o User=${USER} -o RemoteCommand="ls" -P 2222 ${HOST}
